package db.migration;

import org.flywaydb.core.api.migration.Context;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class V4ProjectImagesTest {

    @Test
    void migratesLegacyPicturesAndAddsTheMergedBackendPicture() throws Exception {
        try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:project_images;MODE=PostgreSQL")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("""
                        create table project (
                            project_id bigint generated by default as identity primary key,
                            project_title varchar(160) not null,
                            project_picture varchar(255),
                            project_deleted boolean not null
                        )
                        """);
                statement.execute("""
                        insert into project (project_id, project_title, project_picture, project_deleted) values
                        (1, 'COURIER PLATFORM', 'frontend.png', false),
                        (2, 'BACKEND - COURIER PLATFORM', 'backend.png', true),
                        (3, 'OTHER PROJECT', 'other.png', true)
                        """);
            }

            Context context = mock(Context.class);
            when(context.getConnection()).thenReturn(connection);
            new V4__project_images().migrate(context);

            assertEquals(2, count(connection, "project_id = 1"));
            assertEquals(1, count(connection, "project_id = 3"));
            assertFalse(columnExists(connection, "PROJECT", "PROJECT_PICTURE"));
        }
    }

    private int count(Connection connection, String where) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("select count(*) from project_image where " + where)) {
            result.next();
            return result.getInt(1);
        }
    }

    private boolean columnExists(Connection connection, String table, String column) throws Exception {
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, table, column)) {
            return columns.next();
        }
    }
}
