spring.application.name=keax-portfolio
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:9090}
server.address=${SERVER_ADDRESS:127.0.0.1}
server.error.include-stacktrace=never
server.error.include-message=never

# PostgreSQL database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Connection pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

# Detailed logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.level.org.springframework.web=INFO
logging.level.com.tupackage=INFO
logging.level.org.springframework.boot.context.config=INFO

# CORS setup for development
spring.web.cors.allowed-origins=${URL_FRONTEND}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Timezone Ecuador (UTC-5)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=America/Guayaquil

cloudinary.cloud-name=${CL_NAME}
cloudinary.api-key=${CL_KEY}
cloudinary.api-secret=${CL_SECRET}

# File size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Gmail
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.host=${GM_HOST}
spring.mail.port=${GM_PORT}
spring.mail.username=${GM_USERNAME}
spring.mail.password=${GM_PASSWORD}
spring.mail.properties.mail.smtp.ssl.trust=${GM_TRUST}
spring.mail.to=${GM_TO}

# Clave
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXP}

app.api.url_frontend=${URL_FRONTEND}