package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class V4__project_images extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        createProjectImageTable(connection);

        List<ProjectRow> projects = loadProjects(connection);
        Map<Long, LinkedHashSet<String>> imagesByProject = new LinkedHashMap<>();
        Map<String, Long> activeProjectsByTitle = new LinkedHashMap<>();

        for (ProjectRow project : projects) {
            imagesByProject.put(project.id(), new LinkedHashSet<>());
            addImage(imagesByProject.get(project.id()), project.picture());
            if (!project.deleted()) {
                activeProjectsByTitle.put(normalizeTitle(project.title()), project.id());
            }
        }

        for (ProjectRow project : projects) {
            if (!project.deleted() || !hasLayerPrefix(project.title())) {
                continue;
            }
            Long targetId = activeProjectsByTitle.get(normalizeTitle(project.title()));
            if (targetId != null) {
                addImage(imagesByProject.get(targetId), project.picture());
            }
        }

        insertImages(connection, imagesByProject);
        execute(connection, "alter table project drop column if exists project_picture");
        execute(connection, "create index if not exists idx_project_image_project "
                + "on project_image (project_id, project_image_position)");
    }

    private void createProjectImageTable(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists project_image (
                    project_image_id bigint generated by default as identity primary key,
                    project_id bigint not null,
                    project_image_url varchar(2048) not null,
                    project_image_position integer not null,
                    constraint fk_project_image_project foreign key (project_id)
                        references project (project_id) on delete cascade,
                    constraint uk_project_image_url unique (project_id, project_image_url),
                    constraint uk_project_image_position unique (project_id, project_image_position)
                )
                """);
    }

    private List<ProjectRow> loadProjects(Connection connection) throws SQLException {
        List<ProjectRow> projects = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement("""
                select project_id, project_title, project_picture, project_deleted
                from project
                order by project_id
                """); ResultSet rows = statement.executeQuery()) {
            while (rows.next()) {
                projects.add(new ProjectRow(
                        rows.getLong("project_id"),
                        rows.getString("project_title"),
                        rows.getString("project_picture"),
                        rows.getBoolean("project_deleted")
                ));
            }
        }
        return projects;
    }

    private void insertImages(
            Connection connection,
            Map<Long, LinkedHashSet<String>> imagesByProject
    ) throws SQLException {
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into project_image (project_id, project_image_url, project_image_position)
                values (?, ?, ?)
                """)) {
            for (Map.Entry<Long, LinkedHashSet<String>> entry : imagesByProject.entrySet()) {
                int position = 1;
                for (String url : entry.getValue()) {
                    if (position > 3) {
                        break;
                    }
                    insert.setLong(1, entry.getKey());
                    insert.setString(2, url);
                    insert.setInt(3, position++);
                    insert.addBatch();
                }
            }
            insert.executeBatch();
        }
    }

    private void addImage(LinkedHashSet<String> images, String picture) {
        if (picture != null && !picture.isBlank()) {
            images.add(picture.trim());
        }
    }

    private boolean hasLayerPrefix(String title) {
        if (title == null) {
            return false;
        }
        String normalized = title.trim().toUpperCase(Locale.ROOT);
        return normalized.startsWith("FRONTEND -") || normalized.startsWith("BACKEND -");
    }

    private String normalizeTitle(String title) {
        if (title == null) {
            return "";
        }
        return title.trim()
                .replaceFirst("(?i)^(FRONTEND|BACKEND)\\s*-\\s*", "")
                .trim()
                .toUpperCase(Locale.ROOT);
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private record ProjectRow(long id, String title, String picture, boolean deleted) {
    }
}
