package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class V7__harden_integrity_and_assets extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        execute(connection, "alter table project add column if not exists "
                + "project_published boolean default false not null");
        execute(connection, "update project set project_published = true "
                + "where exists (select 1 from project_image image where image.project_id = project.project_id)");

        widenUrlColumns(connection);
        execute(connection, "alter table visitor alter column visitor_ip type varchar(64)");
        createImageCleanupTable(connection);

        if (isPostgreSql(connection)) {
            createPostgreSqlIntegrityIndexes(connection);
        }
    }

    private void widenUrlColumns(Connection connection) throws SQLException {
        execute(connection, "alter table institution alter column institution_url type varchar(2048)");
        execute(connection, "alter table profile alter column profile_picture type varchar(2048)");
        execute(connection, "alter table skill alter column skill_picture type varchar(2048)");
        execute(connection, "alter table social_network alter column social_network_url type varchar(2048)");
    }

    private void createImageCleanupTable(Connection connection) throws SQLException {
        execute(connection, """
                create table if not exists image_cleanup_task (
                    image_cleanup_task_id bigint generated by default as identity primary key,
                    image_url varchar(2048) not null,
                    attempts integer default 0 not null,
                    last_error varchar(1000),
                    created_at timestamp with time zone not null,
                    updated_at timestamp with time zone not null,
                    constraint uk_image_cleanup_task_url unique (image_url)
                )
                """);
        execute(connection, "create index if not exists idx_image_cleanup_task_created "
                + "on image_cleanup_task (created_at)");
    }

    private void createPostgreSqlIntegrityIndexes(Connection connection) throws SQLException {
        execute(connection, "create unique index if not exists uk_institution_active_name "
                + "on institution (lower(institution_name)) where institution_deleted = false");
        execute(connection, "create unique index if not exists uk_skill_active_name "
                + "on skill (lower(skill_name)) where skill_deleted = false");
        execute(connection, "create unique index if not exists uk_skill_active_position "
                + "on skill (skill_position) where skill_deleted = false");
        execute(connection, "create unique index if not exists uk_technology_active_name "
                + "on technology (lower(technology_name)) where technology_deleted = false");
        execute(connection, "create unique index if not exists uk_social_network_active_name "
                + "on social_network (lower(social_network_name)) where social_network_deleted = false");
        execute(connection, "create unique index if not exists uk_social_network_active_position "
                + "on social_network (social_network_position) where social_network_deleted = false");
        execute(connection, "create unique index if not exists uk_education_active_title_institution "
                + "on education (lower(education_title), institution_id) where education_deleted = false");
        execute(connection, "create unique index if not exists uk_education_active_position "
                + "on education (education_position) where education_deleted = false");
        execute(connection, "create unique index if not exists uk_project_active_title "
                + "on project (lower(project_title)) where project_deleted = false");
        execute(connection, "create unique index if not exists uk_project_active_position "
                + "on project (project_position) where project_deleted = false");
        execute(connection, "create unique index if not exists uk_profile_singleton on profile ((true))");
    }

    private boolean isPostgreSql(Connection connection) throws SQLException {
        return connection.getMetaData().getDatabaseProductName().toLowerCase().contains("postgresql");
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
