alter table profile
    add column profile_specialties varchar(500) not null default '';

alter table profile
    add column profile_summary text not null default '';

alter table profile
    add column profile_summary_es text not null default '';

alter table profile
    add column profile_about text not null default '';

alter table profile
    add column profile_about_es text not null default '';

alter table skill
    add column skill_category varchar(40) not null default 'OTHER';

alter table skill
    add column skill_visible boolean not null default true;

alter table skill
    add constraint chk_skill_category
        check (skill_category in (
            'FRONTEND',
            'BACKEND',
            'DATABASE',
            'DEVOPS_CLOUD',
            'TESTING',
            'ARCHITECTURE',
            'OTHER'
        ));

alter table education
    add column education_visible boolean not null default true;

alter table course
    add column course_visible boolean not null default true;

create table experience (
    experience_id bigint generated by default as identity primary key,
    experience_role varchar(160) not null,
    experience_role_es varchar(160) not null,
    experience_company varchar(160) not null,
    experience_description text not null,
    experience_description_es text not null,
    experience_start varchar(80) not null,
    experience_start_es varchar(80) not null,
    experience_end varchar(80),
    experience_end_es varchar(80),
    experience_position integer not null,
    experience_visible boolean not null default true,
    experience_deleted boolean not null default false,
    version bigint not null default 0,
    constraint chk_experience_position_positive check (experience_position > 0)
);

create index idx_skill_deleted_visible_category_position
    on skill (skill_deleted, skill_visible, skill_category, skill_position);

create index idx_education_deleted_visible_position
    on education (education_deleted, education_visible, education_position);

create index idx_course_deleted_visible_position
    on course (course_deleted, course_visible, course_position);

create index idx_experience_deleted_position
    on experience (experience_deleted, experience_position);

create index idx_experience_deleted_visible_position
    on experience (experience_deleted, experience_visible, experience_position);

update profile
set profile_title = 'Full Stack Developer',
    profile_title_es = 'Desarrollador Full Stack'
where lower(trim(profile_title)) in (
          'information systems engineer',
          'systems engineer'
      )
   or lower(trim(profile_title_es)) in (
          'ingeniero en sistemas de información',
          'ingeniera en sistemas de información',
          'ingeniero en sistemas de informacion',
          'ingeniera en sistemas de informacion'
      );

update profile
set profile_specialties = 'Angular · Spring Boot · Laravel'
where trim(profile_specialties) = '';

update profile
set profile_summary = 'I build enterprise web applications and REST APIs for logistics, transportation and administrative management.',
    profile_summary_es = 'Desarrollo aplicaciones web empresariales y APIs REST para logística, transporte y gestión administrativa.'
where trim(profile_summary) = ''
   or trim(profile_summary_es) = '';

update profile
set profile_about = 'I am a Full Stack Developer with nearly four years of experience building and integrating enterprise solutions. I work primarily with Angular, Spring Boot and Laravel, applying secure authentication, relational databases, automated testing, Docker, CI/CD, hexagonal architecture, DDD, Clean Code and SOLID.',
    profile_about_es = 'Soy Full Stack Developer con cerca de cuatro años de experiencia desarrollando e integrando soluciones empresariales. Trabajo principalmente con Angular, Spring Boot y Laravel, aplicando autenticación segura, bases de datos relacionales, testing automatizado, Docker, CI/CD, arquitectura hexagonal, DDD, Clean Code y SOLID.'
where trim(profile_about) = ''
   or trim(profile_about_es) = '';

update education
set education_title_es = 'Ingeniería en Sistemas de Información'
where lower(trim(education_title_es)) in (
    'ingeniera en sistemas de información',
    'ingeniera en sistemas de informacion',
    'ingeniero en sistemas de información',
    'ingeniero en sistemas de informacion'
);

update education
set education_visible = institution_id in (
    select institution_id
    from institution
    where lower(trim(institution_name)) in (
              'universidad tecnológica israel',
              'universidad tecnologica israel',
              'escuela politécnica nacional',
              'escuela politecnica nacional'
          )
       or lower(trim(institution_name_es)) in (
              'universidad tecnológica israel',
              'universidad tecnologica israel',
              'escuela politécnica nacional',
              'escuela politecnica nacional'
          )
);

update skill
set skill_category = case
    when lower(skill_name) in (
        'angular', 'typescript', 'rxjs', 'javascript', 'angular material',
        'primeng', 'bootstrap', 'tailwind', 'html', 'css'
    ) then 'FRONTEND'
    when lower(skill_name) in (
        'java', 'spring boot', 'laravel', 'php', 'rest api', 'rest apis',
        'spring security', 'jpa', 'hibernate', 'jpa / hibernate'
    ) then 'BACKEND'
    when lower(skill_name) in (
        'oracle', 'oracle database', 'postgresql', 'mysql', 'sql server'
    ) then 'DATABASE'
    when lower(skill_name) in (
        'docker', 'ci/cd', 'git', 'github', 'github actions',
        'oracle visual builder studio', 'aws', 'linux', 'nginx'
    ) then 'DEVOPS_CLOUD'
    when lower(skill_name) in (
        'junit', 'mockito', 'phpunit', 'mockery', 'angular testbed',
        'vitest', 'playwright', 'unit testing', 'integration testing', 'e2e testing'
    ) then 'TESTING'
    when lower(skill_name) in (
        'hexagonal architecture', 'arquitectura hexagonal',
        'domain-driven design', 'domain-driven design (ddd)', 'ddd',
        'layered architecture', 'arquitectura por capas', 'mvc',
        'solid', 'clean code', 'modular design', 'diseño modular'
    ) then 'ARCHITECTURE'
    else 'OTHER'
end;
