create table if not exists institution (
    institution_id bigint generated by default as identity primary key,
    institution_name varchar(255) not null,
    institution_name_es varchar(255),
    institution_url varchar(255),
    institution_deleted boolean not null
);

create table if not exists profile (
    profile_id bigint generated by default as identity primary key,
    profile_name varchar(255) not null,
    profile_last_name varchar(255) not null,
    profile_title varchar(255) not null,
    profile_title_es varchar(255),
    profile_cv varchar(255),
    profile_picture varchar(255)
);

create table if not exists skill (
    skill_id bigint generated by default as identity primary key,
    skill_name varchar(255) not null,
    skill_picture varchar(255),
    skill_position integer not null,
    skill_deleted boolean not null
);

create table if not exists technology (
    technology_id bigint generated by default as identity primary key,
    technology_name varchar(255) not null,
    technology_position integer not null,
    technology_deleted boolean not null
);

create table if not exists social_network (
    social_network_id bigint generated by default as identity primary key,
    social_network_name varchar(255) not null,
    social_network_icon varchar(255) not null,
    social_network_color varchar(255) not null,
    social_network_position integer not null,
    social_network_url varchar(255) not null,
    social_network_deleted boolean not null
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password varchar(255) not null,
    constraint uk_users_username unique (username)
);

create table if not exists visitor (
    visitor_id bigint generated by default as identity primary key,
    visitor_ip varchar(45) not null,
    visitor_country varchar(120),
    visitor_city varchar(120),
    visitor_user_agent varchar(500),
    visitor_path varchar(255),
    visitor_visited_at timestamp with time zone not null
);

create table if not exists education (
    education_id bigint generated by default as identity primary key,
    education_title varchar(255) not null,
    education_title_es varchar(255),
    education_place varchar(255) not null,
    education_start varchar(255),
    education_start_es varchar(255),
    education_end varchar(255) not null,
    education_end_es varchar(255),
    education_position integer not null,
    education_deleted boolean not null,
    institution_id bigint not null,
    constraint fk_education_institution
        foreign key (institution_id) references institution (institution_id)
);

create table if not exists project (
    project_id bigint generated by default as identity primary key,
    project_title varchar(255) not null,
    project_title_es varchar(255),
    project_description text not null,
    project_description_es text,
    project_picture varchar(255),
    project_deploy varchar(255),
    project_github varchar(255),
    project_position integer not null,
    project_deleted boolean not null,
    technology_id bigint not null,
    constraint fk_project_technology
        foreign key (technology_id) references technology (technology_id)
);

create index if not exists idx_institution_deleted_name
    on institution (institution_deleted, institution_name);

create index if not exists idx_education_deleted
    on education (education_deleted);

create index if not exists idx_education_deleted_position
    on education (education_deleted, education_position);

create index if not exists idx_education_institution_deleted
    on education (institution_id, education_deleted);

create index if not exists idx_education_title_deleted_institution
    on education (education_title, education_deleted, institution_id);

create index if not exists idx_skill_deleted_name
    on skill (skill_deleted, skill_name);

create index if not exists idx_skill_deleted_position
    on skill (skill_deleted, skill_position);

create index if not exists idx_technology_deleted_name
    on technology (technology_deleted, technology_name);

create index if not exists idx_technology_deleted_position
    on technology (technology_deleted, technology_position);

create index if not exists idx_project_deleted_title
    on project (project_deleted, project_title);

create index if not exists idx_project_technology_deleted
    on project (technology_id, project_deleted);

create index if not exists idx_project_technology_deleted_position
    on project (technology_id, project_deleted, project_position);

create index if not exists idx_social_network_deleted_name
    on social_network (social_network_deleted, social_network_name);

create index if not exists idx_social_network_deleted_position
    on social_network (social_network_deleted, social_network_position);

create index if not exists idx_visitor_visited_at
    on visitor (visitor_visited_at);

create index if not exists idx_visitor_ip_visited_at
    on visitor (visitor_ip, visitor_visited_at);

create index if not exists idx_visitor_country_visited_at
    on visitor (visitor_country, visitor_visited_at);

create index if not exists idx_visitor_city_visited_at
    on visitor (visitor_city, visitor_visited_at);
