create table if not exists project_technology (
    project_technology_id bigint generated by default as identity primary key,
    project_id bigint not null,
    technology_id bigint not null,
    project_technology_position integer not null,
    constraint fk_project_technology_project
        foreign key (project_id) references project (project_id),
    constraint fk_project_technology_technology
        foreign key (technology_id) references technology (technology_id),
    constraint uk_project_technology unique (project_id, technology_id),
    constraint uk_project_technology_position unique (project_id, project_technology_position)
);

create table if not exists project_link (
    project_link_id bigint generated by default as identity primary key,
    project_id bigint not null,
    project_link_type varchar(40) not null,
    project_link_url varchar(2048) not null,
    project_link_position integer not null,
    constraint fk_project_link_project
        foreign key (project_id) references project (project_id),
    constraint uk_project_link_type unique (project_id, project_link_type),
    constraint uk_project_link_position unique (project_id, project_link_position)
);

insert into project_technology (project_id, technology_id, project_technology_position)
select project_id, technology_id, 1
from project;

insert into project_link (project_id, project_link_type, project_link_url, project_link_position)
select project_id, 'DEPLOY', project_deploy, 1
from project
where project_deploy is not null and trim(project_deploy) <> '';

insert into project_link (project_id, project_link_type, project_link_url, project_link_position)
select
    project_id,
    case
        when upper(project_title) like 'FRONTEND -%' then 'GITHUB_FRONTEND'
        when upper(project_title) like 'BACKEND -%' then 'GITHUB_BACKEND'
        else 'GITHUB'
    end,
    project_github,
    case
        when project_deploy is not null and trim(project_deploy) <> '' then 2
        else 1
    end
from project
where project_github is not null and trim(project_github) <> '';

drop index if exists idx_project_technology_deleted;
drop index if exists idx_project_technology_deleted_position;

alter table project drop constraint if exists fk_project_technology;
alter table project drop column if exists technology_id;
alter table project drop column if exists project_deploy;
alter table project drop column if exists project_github;

create index if not exists idx_project_technology_project
    on project_technology (project_id, project_technology_position);

create index if not exists idx_project_technology_technology
    on project_technology (technology_id, project_id);

create index if not exists idx_project_link_project
    on project_link (project_id, project_link_position);

create index if not exists idx_project_deleted_position
    on project (project_deleted, project_position);
