create table if not exists course (
    course_id bigint generated by default as identity primary key,
    course_name varchar(200) not null,
    course_certificate_url varchar(2048),
    course_deleted boolean not null default false,
    institution_id bigint not null,
    constraint fk_course_institution
        foreign key (institution_id) references institution (institution_id)
);

create index if not exists idx_course_deleted_name
    on course (course_deleted, course_name);

create index if not exists idx_course_institution_deleted
    on course (institution_id, course_deleted);

create index if not exists idx_course_name_deleted_institution
    on course (course_name, course_deleted, institution_id);
